// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxevlwKx31mbu1Vg0pFzdMOcqJJOYtN0U',
    appId: '1:906105436076:web:e06ddd8a3dfcd7d8c4ec09',
    messagingSenderId: '906105436076',
    projectId: 'fir-chat-2d6a5',
    authDomain: 'fir-chat-2d6a5.firebaseapp.com',
    storageBucket: 'fir-chat-2d6a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq2q86N7U5WfAHdi1LQlUqkHoSqhgplyg',
    appId: '1:906105436076:android:92f8fbda8849e222c4ec09',
    messagingSenderId: '906105436076',
    projectId: 'fir-chat-2d6a5',
    storageBucket: 'fir-chat-2d6a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAalaoWx3G_ctw6yBFFuMN9ZgQejgNJkAk',
    appId: '1:906105436076:ios:9a33b8983fbbcf8bc4ec09',
    messagingSenderId: '906105436076',
    projectId: 'fir-chat-2d6a5',
    storageBucket: 'fir-chat-2d6a5.appspot.com',
    iosClientId: '906105436076-rguufk7rtd5r4nr0aqi84r53ra5c2jvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAalaoWx3G_ctw6yBFFuMN9ZgQejgNJkAk',
    appId: '1:906105436076:ios:9a33b8983fbbcf8bc4ec09',
    messagingSenderId: '906105436076',
    projectId: 'fir-chat-2d6a5',
    storageBucket: 'fir-chat-2d6a5.appspot.com',
    iosClientId: '906105436076-rguufk7rtd5r4nr0aqi84r53ra5c2jvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFirebase',
  );
}
